### ISSUE TITLE
java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by gstamatakis** [pradykaushik/Distributed-BankingApplication#1]
./branch.sh branch1 10001
starting branch1 on port : 10001...
<after the controller.sh is run...>
Exception in thread "Thread-0" java.lang.IllegalArgumentException: bound must be positive
        at java.util.Random.nextInt(Random.java:388)
        at BranchServerImpl.getRandomBranch(BranchServerImpl.java:303)
        at BranchServerImpl.access$300(BranchServerImpl.java:13)
        at BranchServerImpl$1MoneyTransferTimer.run(BranchServerImpl.java:256)
        at BranchServerImpl.scheduleMoneyTransfers(BranchServerImpl.java:277)
        at BranchServerImpl.access$000(BranchServerImpl.java:13)
        at BranchServerImpl$1.run(BranchServerImpl.java:80)
        at java.lang.Thread.run(Thread.java:745)

**Comment by pradykaushik** [comment]
Can you please share your branches.txt?

This is a possible bug. How many branches do you have? It's possible that you have only branch and this might a corner case that might need to be taken care of.

**Comment by gstamatakis** [comment]
My branches.txt has 2-3 branches inside my network.
They are named and placed like that:

branch1 192.168.1.101 10001
branch2 192.168.1.102 10002

I think the error was also "Can not INIT branch.." or something like that.

Thank you for your time.

**Comment by pradykaushik** [comment]
Are you sure that the IP addresses 192.168.1.101 and 192.168.1.102 are correct? Are they in the same network as the controller?

**Comment by gstamatakis** [comment]
Botha accessible and valid.
Verified that by pinging them.
Also the ports are open.

**Comment by pradykaushik** [comment]
Alright. Are all the branches up and running before the controller?

**Comment by pradykaushik** [comment]
So follow the steps below
1. Make sure branches.txt contains the correct port numbers and IP address of the branches.
branches.txt should have the following format

```
<branch-name1> <ip address1> <port1>
<branch-name2> <ip address2> <port2>
...
```

2. Run each branch using the command `./branch.sh <branch name> <port number>`
3. Run the controller using the command `bash controller.sh <amount to initialize> branches.txt`

Let me know if this works for you.
